// Generated by Melange
"use strict";

var React = require("react");
var PageWelcome = require("./PageWelcome.js");

function Shared$App(Props) {
  return React.createElement(PageWelcome.make, {});
}

var App = {
  make: Shared$App,
};

exports.App = App;
/* react Not a pure module */
